### ISSUE TITLE
Line endings not handled properly in FileUtilities.create and FileUtilities.append

### ISSUE THREAD

**Issue by astrohart** [iadgov/WALKOFF-Apps#13]
When I enter text as static content to the create file and append file actions of the FileUtilities app in WALKOFF, it seems like a newline (of course, must be specific to the operating system, because Linux uses LFs as text newlines and Windows uses a CR-LF pair) should be emitted at the end of the content, and there isn't one.

**Comment by astrohart** [comment]
As an aside, I notice that, in general, the file handling is done in such a way that great pains are being taken to respect the specific way whatever OS the code is running on does things.  And yet we have a ```f.write("\n")``` line in ```append``` just assuming that a Linux-style LF is the proper newline character.

**Comment by krzim** [comment]
Please see https://github.com/nsacyber/WALKOFF-Apps/pull/14#issuecomment-470210596
